<a href="https://colab.research.google.com/github/andrea212023/ML-Kis/blob/main/HW_2_1_Matrices_and_vectors_KIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [29]:
import numpy as np

# Task 1: Create a vector with 10 random float values between 0 and 1
vector = np.random.rand(10)  # Using np.random.rand as an alternative to random.uniform
print("Vector:", vector)
print("Size of vector:", vector.size)

# Task 2: Create a 3x3 matrix with specified values
matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])
print("\nMatrix:\n", matrix)
print("Size of matrix:", matrix.shape)


Vector: [0.62736289 0.96829693 0.78693949 0.09112663 0.35778188 0.12229678
 0.86090324 0.18719853 0.9864471  0.55515442]
Size of vector: 10

Matrix:
 [[11 14 17]
 [20 23 26]
 [29 32 35]]
Size of matrix: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [30]:
# Task 1: Add 10 to each element in 'vector' and round to 2 decimal places without loops
vector_updated = np.round(vector + 10, 2)
print("Updated Vector (each element +10, rounded to 2 decimal places):", vector_updated)

# Task 2: Multiply each element in 'matrix' by 2 without loops
matrix_doubled = matrix * 2
print("\nMatrix after multiplying each element by 2:\n", matrix_doubled)

# Task 3: Create a new vector with the square of each element in 'vector' without loops
vector_squared = np.square(vector)
print("\nNew Vector (square of each element in original vector):", vector_squared)

Updated Vector (each element +10, rounded to 2 decimal places): [10.63 10.97 10.79 10.09 10.36 10.12 10.86 10.19 10.99 10.56]

Matrix after multiplying each element by 2:
 [[22 28 34]
 [40 46 52]
 [58 64 70]]

New Vector (square of each element in original vector): [0.39358419 0.93759895 0.61927375 0.00830406 0.12800787 0.0149565
 0.7411544  0.03504329 0.97307787 0.30819643]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [31]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [32]:
import numpy as np

# Define matrices A, B, C, and D
A = np.array([
    [0.18, 0.53],
    [0.75, 0.47],
    [0.35, 0.21]
])

B = np.array([
    [0.17, 0.58, 0.75],
    [0.38, 0.11, 0.15]
])

C = np.array([[0], [1]])
D = np.array([[0, 1], [1, 0]])

# Task 1: Matrix multiplication of A (3x2) and B (2x3) to get a 3x3 result
result_matrix = np.dot(A, B)
print("Resulting Matrix (A * B):\n", result_matrix)

# Task 2: Element-wise multiplication using the second column of result_matrix and vector C
# Since result_matrix is 3x3, we use the second column (index 1) to match the size of C
result_C = result_matrix[:2, 1] * C.flatten()  # Multiply first two elements of the second column by C
print("\nResult of element-wise multiplication of second column of result_matrix with C:\n", result_C)

# Task 3: Extract the top left 2x2 submatrix from result_matrix and multiply with D
sub_matrix = result_matrix[:2, :2]
result_D = np.dot(sub_matrix, D)
print("\nResult of sub_matrix * D:\n", result_D)

Resulting Matrix (A * B):
 [[0.232  0.1627 0.2145]
 [0.3061 0.4867 0.633 ]
 [0.1393 0.2261 0.294 ]]

Result of element-wise multiplication of second column of result_matrix with C:
 [0.     0.4867]

Result of sub_matrix * D:
 [[0.1627 0.232 ]
 [0.4867 0.3061]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [28]:
# Task 1: Transpose result_matrix
transposed_result_matrix = result_matrix.T
print("Transposed Result Matrix:\n", transposed_result_matrix)

# Task 2: Transpose vector and display its shape
vector = np.array([0.00536347, 0.60759359, 0.76038058, 0.08194031, 0.55495752,
                   0.03772046, 0.31577501, 0.23608649, 0.84148527, 0.63809837])
transposed_vector = vector.T
print("\nTransposed Vector:\n", transposed_vector)
print("Shape of transposed vector:", transposed_vector.shape)  # There's no change in shape when transposing a 1D array

# Task 3: Use numpy.expand_dims on vector with axis=1
column_vector = np.expand_dims(vector, axis=1)
print("\nColumn Vector:\n", column_vector)
print("Shape of column vector:", column_vector.shape)

# Task 4: Transpose column_vector and display result with dimensions
transposed_column_vector = column_vector.T
print("\nTransposed Column Vector:\n", transposed_column_vector)
print("Shape of transposed column vector:", transposed_column_vector.shape)

Transposed Result Matrix:
 [[0.232  0.3061 0.1393]
 [0.1627 0.4867 0.2261]
 [0.2145 0.633  0.294 ]]

Transposed Vector:
 [0.00536347 0.60759359 0.76038058 0.08194031 0.55495752 0.03772046
 0.31577501 0.23608649 0.84148527 0.63809837]
Shape of transposed vector: (10,)

Column Vector:
 [[0.00536347]
 [0.60759359]
 [0.76038058]
 [0.08194031]
 [0.55495752]
 [0.03772046]
 [0.31577501]
 [0.23608649]
 [0.84148527]
 [0.63809837]]
Shape of column vector: (10, 1)

Transposed Column Vector:
 [[0.00536347 0.60759359 0.76038058 0.08194031 0.55495752 0.03772046
  0.31577501 0.23608649 0.84148527 0.63809837]]
Shape of transposed column vector: (1, 10)
